# Site data

title: "UP System Information Technology Foundation"
titleAlt: "UPSITF"
titleFull: "UP System Information Technology Foundation, Inc."


baseurl: http://toffmendoza.me/sandbox-upsitf
#baseurl: https://upsitf.org

# Build settings
markdown: kramdown
permalink: pretty

# Site settings
headerDropdown: false

switchBlog: false
switchAnchorSlash: true

fileSchedule: "UPSITFShortCourses20171028.pdf"

urlRegForm: "https://sitf.typeform.com/to/tXnMb4"
urlRegFormMini: "http://bit.ly/upsitf-register"

urlFacebook: "https://www.facebook.com/upsitf.org"
urlTwitter: "https://twitter.com/upsitf"

urlY4iT: "https://y4it.org"
urlY4iTFacebook: "https://facebook.com/ilove.Y4iT"
urlY4iTTwitter: "https://twitter.com/y4it"
urlY4iTInstagram: "https://instagram.com/y4it"
contactY4iTEmailInfo: "info@y4it.org"
contactY4iTEmailMarketing: "marketing@y4it.org"

urlTBC4K: "https://tbc4k.upsitf.org"
urlTBC4KFacebook: "https://facebook.com/tbc4k"

contactAddress:
 - "Rm. 303 Vidal Tan Hall"
 - "Quirino Ave. cor. Velasquez St."
 - "UP Diliman, Quezon City"
contactHours:
 - "8am to 5pm"
contactEmail: "info@upsitf.org"
contactEmailMarketing: "marketing@upsitf.org"
contactLandlineMain: (02) 788 5898
contactLandlineSub: (02) 436 2217
contactFax: (02) 920 2036
contactMobile: 0917 563 5682
